name: spacegame
description: A space strategy game client.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  web_socket_channel: ^3.0.0
  http: ^1.1.0
  uuid: ^4.2.2
  shared_preferences: ^2.2.2
  flutter_slidable: ^4.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
