package planet_survey

import (
	"context"
	"database/sql"
	_ "embed"
	"encoding/json"
	"fmt"
	"log"
	"regexp"
	"strings"
	"time"

	"spacegame/internal/db"
	"spacegame/internal/openai"

	"github.com/google/uuid"
)

//go:embed expedition_event_prompt.txt
var promptTemplate string

const (
	MaxInventory    = 1000.0
	MaxLLMRetries   = 5
	MaxChainDepth   = 6
	MaxActiveChains = 1
)

var ValidInventoryResources = []string{"food", "iron", "composite", "mechanisms", "reagents"}

// ExpeditionPlanet is the minimal planet interface needed for expedition chain operations.
type ExpeditionPlanet interface {
	GetID() string
	GetOwnerID() string
	GetName() string
	GetDescription() string
	GetLevel() int
	GetResourceType() string
	GetResources() map[string]*float64
	AddResource(res string, amount float64)
}

// ExpeditionChain represents a running/completed expedition event chain.
type ExpeditionChain struct {
	ID                 string
	PlanetID           string
	OwnerID            string
	Status             string // "active" | "completed" | "failed"
	EventCount         int
	CurrentEventIndex  int
	Events             []ExpeditionEvent
	DiscoveredLocation *Location
	Inventory          map[string]float64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

// ExpeditionEvent represents a single event generated by LLM.
type ExpeditionEvent struct {
	EventID         string
	Description     string
	ImmediateReward map[string]float64
	Choices         []ExpeditionChoice
	IsEnd           bool
	LocationReward  string
	// RewardsReceived stores the rewards from the player's choice.
	RewardsReceived map[string]float64
	// PlayerChoice stores the index of the player's selected choice.
	PlayerChoice int
}

// ExpeditionChoice represents a player choice within an event.
type ExpeditionChoice struct {
	Label       string
	Description string
	Reward      map[string]float64
	NextEventID string
}

// rawEventResponse is the JSON structure returned by LLM.
type rawEventResponse struct {
	EventID         string                 `json:"event_id"`
	Description     string                 `json:"description"`
	ImmediateReward map[string]interface{} `json:"immediate_reward"`
	Choices         []rawChoice            `json:"choices"`
	IsEnd           bool                   `json:"is_end"`
	LocationReward  string                 `json:"location_reward"`
}

type rawChoice struct {
	Label       string                 `json:"label"`
	Description string                 `json:"description"`
	Reward      map[string]interface{} `json:"reward"`
	NextEventID string                 `json:"next_event_id"`
}

// ValidateInventory checks that the inventory is valid for an expedition.
func ValidateInventory(inventory map[string]float64) error {
	if len(inventory) == 0 {
		return fmt.Errorf("inventory cannot be empty")
	}

	total := 0.0
	for res, amount := range inventory {
		if amount < 0 {
			return fmt.Errorf("inventory amount for %s cannot be negative", res)
		}
		if amount > 0 {
			valid := false
			for _, v := range ValidInventoryResources {
				if v == res {
					valid = true
					break
				}
			}
			if !valid {
				return fmt.Errorf("unknown resource in inventory: %s", res)
			}
		}
		total += amount
	}

	if total <= 0 {
		return fmt.Errorf("inventory total must be greater than 0")
	}
	if total > MaxInventory {
		return fmt.Errorf("inventory total %.0f exceeds maximum %.0f", total, MaxInventory)
	}

	return nil
}

// GetInventorySize returns the total size of the inventory.
func GetInventorySize(inventory map[string]float64) float64 {
	total := 0.0
	for _, amount := range inventory {
		total += amount
	}
	return total
}

// ParseReward parses a raw reward map from LLM into a flat resource map.
func ParseReward(raw map[string]interface{}) (map[string]float64, error) {
	result := make(map[string]float64)

	// Try nested format: {"resources": {"reagents": 50, "food": -10}}
	if resources, ok := raw["resources"]; ok {
		if resMap, ok := resources.(map[string]interface{}); ok {
			for res, val := range resMap {
				if !isValidResource(res) {
					continue
				}
				if f, ok := toFloat64(val); ok {
					result[res] = f
				}
			}
			return result, nil
		}
	}

	// Try flat format: {"reagents": 50, "food": -10}
	for res, val := range raw {
		if !isValidResource(res) {
			continue
		}
		if f, ok := toFloat64(val); ok {
			result[res] = f
		}
	}

	return result, nil
}

func isValidResource(res string) bool {
	for _, v := range ValidInventoryResources {
		if v == res {
			return true
		}
	}
	return false
}

func toFloat64(val interface{}) (float64, bool) {
	switch v := val.(type) {
	case float64:
		return v, true
	case int:
		return float64(v), true
	case int64:
		return float64(v), true
	case json.Number:
		f, err := v.Float64()
		if err != nil {
			return 0, false
		}
		return f, true
	default:
		return 0, false
	}
}

// ApplyRewardToInventory applies a reward to the inventory with clamping.
func ApplyRewardToInventory(inventory map[string]float64, reward map[string]float64) {
	for res, amount := range reward {
		inventory[res] += amount
		if inventory[res] < 0 {
			inventory[res] = 0
		}
	}

	// Clamp to max inventory
	total := GetInventorySize(inventory)
	if total > MaxInventory {
		scale := MaxInventory / total
		for res := range inventory {
			inventory[res] *= scale
		}
	}
}

// ParseEventResponse parses the raw LLM response into an ExpeditionEvent.
func ParseEventResponse(raw string) (*ExpeditionEvent, error) {
	// Remove markdown code block if present
	cleaned := strings.TrimSpace(raw)
	markdownRe := regexp.MustCompile("(?s)```(?:json)?\\s*\\n?(.*?)\\n?```")
	matches := markdownRe.FindStringSubmatch(cleaned)
	if len(matches) > 1 {
		cleaned = strings.TrimSpace(matches[1])
	}

	// Try to find JSON in the response (find first { to last })
	firstBrace := strings.IndexAny(cleaned, "{")
	lastBrace := strings.LastIndexAny(cleaned, "}")
	if firstBrace == -1 || lastBrace == -1 || firstBrace >= lastBrace {
		return nil, fmt.Errorf("no JSON found in LLM response")
	}
	jsonMatch := cleaned[firstBrace : lastBrace+1]

	var rawEvt rawEventResponse
	if err := json.Unmarshal([]byte(jsonMatch), &rawEvt); err != nil {
		return nil, fmt.Errorf("failed to parse LLM response as JSON: %w", err)
	}

	if rawEvt.Description == "" {
		return nil, fmt.Errorf("LLM response missing description")
	}

	// Parse immediate reward
	immediateReward := make(map[string]float64)
	if rawEvt.ImmediateReward != nil {
		parsed, err := ParseReward(rawEvt.ImmediateReward)
		if err != nil {
			return nil, fmt.Errorf("failed to parse immediate_reward: %w", err)
		}
		immediateReward = parsed
	}

	// Parse choices
	choices := make([]ExpeditionChoice, 0, len(rawEvt.Choices))
	for _, rc := range rawEvt.Choices {
		reward := make(map[string]float64)
		if rc.Reward != nil {
			parsed, err := ParseReward(rc.Reward)
			if err != nil {
				return nil, fmt.Errorf("failed to parse choice reward: %w", err)
			}
			reward = parsed
		}
		choices = append(choices, ExpeditionChoice{
			Label:       rc.Label,
			Description: rc.Description,
			Reward:      reward,
			NextEventID: rc.NextEventID,
		})
	}

	// Validate choice count
	if !rawEvt.IsEnd && (len(choices) < 2 || len(choices) > 4) {
		return nil, fmt.Errorf("invalid choice count: %d (expected 2-4 for non-end event)", len(choices))
	}

	return &ExpeditionEvent{
		EventID:         uuid.New().String(),
		Description:     rawEvt.Description,
		ImmediateReward: immediateReward,
		Choices:         choices,
		IsEnd:           rawEvt.IsEnd,
		LocationReward:  rawEvt.LocationReward,
	}, nil
}

// GenerateEventWithRetry calls LLM with retry logic.
func GenerateEventWithRetry(prompt string) (*ExpeditionEvent, error) {
	client := openai.New()
	ctx, cancel := context.WithTimeout(context.Background(), 300*time.Second)
	defer cancel()

	var lastErr error
	for attempt := 0; attempt < MaxLLMRetries; attempt++ {
		if attempt > 0 {
			delay := time.Duration(1<<uint(attempt-1)) * time.Second
			if delay > 16*time.Second {
				delay = 16 * time.Second
			}
			log.Printf("LLM retry attempt %d/%d after %v", attempt+1, MaxLLMRetries, delay)
			time.Sleep(delay)
		}

		log.Printf("LLM prompt (attempt %d, %d chars): %s", attempt+1, len(prompt), prompt)

		result, err := client.Chat(ctx, prompt)
		if err != nil {
			lastErr = fmt.Errorf("LLM call failed: %w", err)
			log.Printf("LLM call failed: %v", err)
			continue
		}

		log.Printf("LLM raw response (attempt %d): %s", attempt+1, result)

		event, err := ParseEventResponse(result)
		if err != nil {
			lastErr = fmt.Errorf("failed to parse LLM response: %w", err)
			log.Printf("Failed to parse LLM response: %v", err)
			continue
		}

		return event, nil
	}

	return nil, fmt.Errorf("LLM generation failed after %d retries: %w", MaxLLMRetries, lastErr)
}

// BuildPrompt builds the LLM prompt for generating an expedition event.
func BuildPrompt(planet ExpeditionPlanet, inventory map[string]float64, events []ExpeditionEvent) string {
	ctx := map[string]interface{}{
		"planet_name":          planet.GetName(),
		"planet_description":   planet.GetDescription(),
		"planet_level":         planet.GetLevel(),
		"planet_resource_type": planet.GetResourceType(),
		"inventory":            inventory,
		"events":               events,
		"expedition_depth":     len(events),
		"max_depth":            MaxChainDepth,
	}

	ctxJSON, _ := json.MarshalIndent(ctx, "", "  ")

	return strings.ReplaceAll(promptTemplate, "{{CONTEXT}}", string(ctxJSON))
}

// CreateExpeditionChain creates a new expedition chain without generating an event.
// The chain is saved with status "generating" and event generation is done asynchronously.
func CreateExpeditionChain(planet ExpeditionPlanet, inventory map[string]float64) (*ExpeditionChain, error) {
	if err := ValidateInventory(inventory); err != nil {
		return nil, err
	}

	// Deep copy inventory
	invCopy := make(map[string]float64)
	for k, v := range inventory {
		invCopy[k] = v
	}

	chain := &ExpeditionChain{
		ID:           uuid.New().String(),
		PlanetID:     planet.GetID(),
		OwnerID:      planet.GetOwnerID(),
		Status:       "generating",
		EventCount:   0,
		Inventory:    invCopy,
		Events:       make([]ExpeditionEvent, 0),
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	}

	return chain, nil
}

// GenerateEvent generates the first event for a chain via LLM and updates the chain.
// This should be called asynchronously after CreateExpeditionChain.
func GenerateEvent(chain *ExpeditionChain, planet ExpeditionPlanet) (*ExpeditionEvent, error) {
	prompt := BuildPrompt(planet, chain.Inventory, chain.Events)
	event, err := GenerateEventWithRetry(prompt)
	if err != nil {
		FailChain(chain)
		return nil, fmt.Errorf("failed to generate first event: %w", err)
	}

	// Apply immediate reward
	ApplyRewardToInventory(chain.Inventory, event.ImmediateReward)

	// Save event to chain
	chain.Events = append(chain.Events, *event)
	chain.EventCount = len(chain.Events)
	chain.CurrentEventIndex = 0
	chain.Status = "active"
	chain.UpdatedAt = time.Now()

	return event, nil
}

// StartExpeditionChain creates a new expedition chain and generates the first event.
func StartExpeditionChain(planet ExpeditionPlanet, inventory map[string]float64) (*ExpeditionChain, *ExpeditionEvent, error) {
	chain, err := CreateExpeditionChain(planet, inventory)
	if err != nil {
		return nil, nil, err
	}

	event, err := GenerateEvent(chain, planet)
	if err != nil {
		return nil, nil, err
	}

	return chain, event, nil
}

// RecordChoice records the player's choice on the current event.
// Call this first, then GenerateNextEvent to generate the next event asynchronously.
func RecordChoice(chain *ExpeditionChain, choiceIndex int) error {
	if chain.CurrentEventIndex < 0 || chain.CurrentEventIndex >= len(chain.Events) {
		return fmt.Errorf("no current event")
	}

	currentEvent := &chain.Events[chain.CurrentEventIndex]
	if choiceIndex < 0 || choiceIndex >= len(currentEvent.Choices) {
		return fmt.Errorf("invalid choice index: %d", choiceIndex)
	}

	choice := currentEvent.Choices[choiceIndex]

	// Record player choice and rewards
	currentEvent.PlayerChoice = choiceIndex
	currentEvent.RewardsReceived = make(map[string]float64)
	for k, v := range choice.Reward {
		currentEvent.RewardsReceived[k] = v
	}

	// Apply choice reward
	ApplyRewardToInventory(chain.Inventory, choice.Reward)

	return nil
}

// GenerateNextEvent generates the next event after a choice has been recorded.
// This should be called asynchronously after RecordChoice.
// Returns nil if the chain ended (is_end event).
func GenerateNextEvent(chain *ExpeditionChain, planet ExpeditionPlanet) (*ExpeditionEvent, error) {
	// Check if this is the end event
	currentEvent := &chain.Events[chain.CurrentEventIndex]
	if currentEvent.IsEnd {
		var location *Location
		if currentEvent.LocationReward != "" {
			locType := currentEvent.LocationReward
			sourceAmount := CalculateSourceAmount(locType, PlanetResourceType(planet.GetResourceType()))
			var sourceResource string
			for _, lt := range GetLocationTypes() {
				if lt.Type == locType {
					sourceResource = lt.SourceResource
					break
				}
			}
			location = &Location{
				ID:              planet.GetID() + "_loc_" + time.Now().Format("20060102150405"),
				PlanetID:        planet.GetID(),
				OwnerID:         planet.GetOwnerID(),
				Type:            locType,
				Name:            GenerateName(locType),
				SourceResource:  sourceResource,
				SourceAmount:    sourceAmount,
				SourceRemaining: sourceAmount,
				Active:          true,
				BuildingActive:  false,
				DiscoveredAt:    time.Now(),
				CreatedAt:       time.Now(),
				UpdatedAt:       time.Now(),
				Buildings:       make([]*LocationBuilding, 0),
			}
		}

		CompleteChain(chain, location)
		return nil, nil
	}

	// Generate next event
	prompt := BuildPrompt(planet, chain.Inventory, chain.Events)
	nextEvent, err := GenerateEventWithRetry(prompt)
	if err != nil {
		FailChain(chain)
		return nil, fmt.Errorf("failed to generate next event: %w", err)
	}

	// Apply immediate reward
	ApplyRewardToInventory(chain.Inventory, nextEvent.ImmediateReward)

	// Save to chain
	chain.Events = append(chain.Events, *nextEvent)
	chain.EventCount = len(chain.Events)
	chain.CurrentEventIndex++
	chain.Status = "active"
	chain.UpdatedAt = time.Now()

	return nextEvent, nil
}

// ResolveChoice processes a player's choice and generates the next event.
func ResolveChoice(chain *ExpeditionChain, planet ExpeditionPlanet, choiceIndex int) (*ExpeditionEvent, error) {
	if err := RecordChoice(chain, choiceIndex); err != nil {
		return nil, err
	}
	return GenerateNextEvent(chain, planet)
}

// CompleteChain marks the chain as completed.
func CompleteChain(chain *ExpeditionChain, location *Location) {
	chain.Status = "completed"
	chain.DiscoveredLocation = location
	chain.UpdatedAt = time.Now()
}

// FailChain marks the chain as failed.
func FailChain(chain *ExpeditionChain) {
	chain.Status = "failed"
	chain.UpdatedAt = time.Now()
}

// ReturnInventoryToPlanet returns the expedition inventory back to the planet.
func ReturnInventoryToPlanet(planet ExpeditionPlanet, inventory map[string]float64) {
	resources := planet.GetResources()
	for res, amount := range inventory {
		if amount <= 0 {
			continue
		}
		planet.AddResource(res, amount)
	}
	_ = resources
}

// GetCurrentEvent returns the current event for a chain.
func GetCurrentEvent(chain *ExpeditionChain) *ExpeditionEvent {
	if chain.CurrentEventIndex < 0 || chain.CurrentEventIndex >= len(chain.Events) {
		return nil
	}
	return &chain.Events[chain.CurrentEventIndex]
}

// GetEventHistory returns a copy of all events in the chain.
func GetEventHistory(chain *ExpeditionChain) []ExpeditionEvent {
	result := make([]ExpeditionEvent, len(chain.Events))
	copy(result, chain.Events)
	return result
}

// --- Database persistence ---

// SaveChainToDB saves an expedition chain to the expedition_chains table.
func SaveChainToDB(chain *ExpeditionChain, db *db.Database) error {
	_, err := db.Exec(`
		INSERT INTO expedition_chains (id, planet_id, owner_id, status, event_count,
			current_event_index, discovered_location_id, inventory, created_at, updated_at)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
		ON CONFLICT (id) DO UPDATE
		SET status = $4, event_count = $5, current_event_index = $6,
			discovered_location_id = $7, inventory = $8, updated_at = $10
	`,
		chain.ID, chain.PlanetID, chain.OwnerID, chain.Status,
		chain.EventCount, chain.CurrentEventIndex,
		toNullUUID(chain.DiscoveredLocation),
		marshalJSONB(chain.Inventory),
		chain.CreatedAt, chain.UpdatedAt,
	)
	return err
}

// SaveEventsToDB saves all events for a chain to the expedition_events table.
func SaveEventsToDB(chainID string, events []ExpeditionEvent, db *db.Database) error {
	// Delete existing events first
	_, err := db.Exec(`DELETE FROM expedition_events WHERE chain_id = $1`, chainID)
	if err != nil {
		return err
	}

	for i, event := range events {
		var rewardsReceived interface{} = marshalJSONB(event.ImmediateReward)
		if len(event.RewardsReceived) > 0 {
			rewardsReceived = marshalJSONB(event.RewardsReceived)
		}
		var playerChoice interface{} = nil
		if event.PlayerChoice > 0 {
			playerChoice = event.PlayerChoice
		}
		_, err := db.Exec(`
			INSERT INTO expedition_events (id, chain_id, event_id, description, choices,
				immediate_reward, is_end, location_reward, player_choice, rewards_received, created_at)
			VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
		`,
			uuid.New().String(),
			chainID,
			event.EventID,
			event.Description,
			marshalJSONB(event.Choices),
			marshalJSONB(event.ImmediateReward),
			event.IsEnd,
			event.LocationReward,
			playerChoice,
			rewardsReceived,
			time.Now().Add(-time.Duration(len(events)-i) * time.Minute),
		)
		if err != nil {
			return err
		}
	}

	return nil
}

// LoadActiveChains loads all active or generating expedition chains for a planet from DB.
func LoadActiveChains(planetID string, db *db.Database) ([]*ExpeditionChain, error) {
	rows, err := db.Query(`
		SELECT id, planet_id, owner_id, status, event_count,
			current_event_index, inventory, created_at, updated_at
		FROM expedition_chains
		WHERE planet_id = $1 AND status IN ('active', 'generating')
	`, planetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	chains := make([]*ExpeditionChain, 0)
	for rows.Next() {
		var chain ExpeditionChain
		var inventoryJSON []byte

		err := rows.Scan(
			&chain.ID, &chain.PlanetID, &chain.OwnerID, &chain.Status,
			&chain.EventCount, &chain.CurrentEventIndex,
			&inventoryJSON, &chain.CreatedAt, &chain.UpdatedAt,
		)
		if err != nil {
			return nil, err
		}

		chain.Inventory = make(map[string]float64)
		if len(inventoryJSON) > 0 {
			json.Unmarshal(inventoryJSON, &chain.Inventory)
		}

		// Load events for this chain
		events, err := LoadChainEvents(chain.ID, db)
		if err != nil {
			log.Printf("Error loading events for chain %s: %v", chain.ID, err)
		}
		chain.Events = events

		chains = append(chains, &chain)
	}

	return chains, rows.Err()
}

// LoadChainEvents loads all events for a chain from DB.
func LoadChainEvents(chainID string, db *db.Database) ([]ExpeditionEvent, error) {
	rows, err := db.Query(`
		SELECT event_id, description, choices, immediate_reward, is_end, location_reward,
			player_choice, rewards_received
		FROM expedition_events
		WHERE chain_id = $1
		ORDER BY created_at ASC
	`, chainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	events := make([]ExpeditionEvent, 0)
	for rows.Next() {
		var event ExpeditionEvent
		var choicesJSON, rewardJSON, receivedJSON []byte
		var playerChoice sql.NullInt64

		err := rows.Scan(
			&event.EventID, &event.Description,
			&choicesJSON, &rewardJSON,
			&event.IsEnd, &event.LocationReward,
			&playerChoice, &receivedJSON,
		)
		if err != nil {
			return nil, err
		}

		event.ImmediateReward = make(map[string]float64)
		if len(rewardJSON) > 0 {
			json.Unmarshal(rewardJSON, &event.ImmediateReward)
		}

		event.Choices = make([]ExpeditionChoice, 0)
		if len(choicesJSON) > 0 {
			json.Unmarshal(choicesJSON, &event.Choices)
		}

		event.PlayerChoice = int(playerChoice.Int64)
		event.RewardsReceived = make(map[string]float64)
		if len(receivedJSON) > 0 {
			json.Unmarshal(receivedJSON, &event.RewardsReceived)
		}

		events = append(events, event)
	}

	return events, rows.Err()
}

func toNullUUID(loc *Location) interface{} {
	if loc == nil {
		return nil
	}
	return loc.ID
}

func marshalJSONB(v interface{}) []byte {
	data, err := json.Marshal(v)
	if err != nil {
		return []byte("{}")
	}
	return data
}
